Return a Promise.reject instead of undefined to avoid the error '￼networked-audio-source.js:78 Uncaught (in promise) TypeError: NAF.connection.adapter.getMediaStream is not a function'